#!/usr/bin/env python

import sys, os

args = sys.argv[1:]
obj = [a for a in args if a.endswith('.o') or a.endswith('.a')]

lib, obj = obj[0], obj[1:]

if obj:
    os.system(" ".join(['libtool -static -c -o', lib, *obj]))
else:
    open(lib, 'w')  # empty file
