#!/usr/bin/env python

import sys
import os

out, cc, cflags, ldflags, obj, lib = sys.argv[1:7]

def nonempty(filename):
    try:
        return os.stat(filename).st_size > 0
    except Exception as e:
        print(filename, e)
        return False


obj = [fn for fn in obj.split() if nonempty(fn)]
lib = [fn for fn in lib.split() if nonempty(fn)]

os.system(" ".join([cc, '-o', out, cflags, ldflags, *obj, *lib]))
